name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Install Dependencies
        run: npx pnpm i
      - name: Build code
        run: npx pnpm build
